// files/vue/components/TodoItem.vue
<template>
  <div :key="todo.id" class="todo-item" :class="{ completed: todo.completed }" @click="toggleTodo(todo)">
    <span :style="{ textDecorationLine: todo.completed ? 'line-through' : 'none' }">{{ todo.title }}</span>
    <div className="remove-button" @click="removeTodo(todo)">X</div>
  </div>
</template>
<script setup>
defineProps({
  todo: {
    type: Object,
    required: true,
  },
  toggleTodo: {
    type: Function,
    required: true,
  },
  removeTodo: {
    type: Function,
    required: true,
  },
});
</script>

// a/src/renderer/components/TodoItem.tsx
import React from 'react';
import { useDispatch } from 'react-redux';
import { remove, toggle, todoItem } from '@/renderer/store/slices/todos';

function Todo({ todo }: { todo: todoItem }) {
  const dispatch = useDispatch();
  return (
    <div
      key={todo.id}
      className={'todo-item' + (todo.completed ? ' completed' : '')}
      onClick={() => dispatch(toggle({ id: todo.id }))}
    >
      <span style={{ textDecorationLine: todo.completed ? 'line-through' : 'none' }}>{todo.title}</span>
      <div className="remove-button" onClick={() => dispatch(remove({ id: todo.id }))}>
        X
      </div>
    </div>
  );
}

export default Todo;
