// a/src/components/todo.tsx
import React, { useState } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import { add } from '@/store/slices/todos';
import { RootState } from '@/store';
import './todo.scss';
import TodoItem from './todoItem';

function Todo() {
  const todosList = useSelector((state: RootState) => state.todos.list);
  const dispatch = useDispatch();
  const [addTodoName, setAddTodoName] = useState('');
  function addTask() {
    dispatch(add({ id: Date.now(), title: addTodoName, completed: false }));
    setAddTodoName('');
  }
  return (
    <div className="todo">
      <div className="title">Example todo app</div>
      <div className="add-todo">
        <input placeholder="Add new task" value={addTodoName} onChange={e => setAddTodoName(e.target.value)} />
        <div className="btn" onClick={addTask}>
          Add task
        </div>
      </div>
      <div className="todos">
        {todosList.map(todo => (
          <TodoItem key={todo.id} todo={todo} />
        ))}
      </div>
    </div>
  );
}

export default Todo;

// files/vue2-vuex/views/Todo.vue
<template>
  <div class="todo">
    <div class="title">Example todo app</div>
    <div class="add-todo">
      <input v-model="addTodoName" placeholder="Add new task" />
      <div class="btn" @click="addTask">Add task</div>
    </div>
    <div class="todos">
      <TodoItem v-for="todo of todoList" :key="todo.id" :todo="todo" />
    </div>
  </div>
</template>

<script>
import TodoItem from '@/components/TodoItem.vue';
export default {
  components: {
    TodoItem,
  },
  data() {
    return {
      addTodoName: '',
    };
  },
  computed: {
    todoList() {
      return this.$store.state.todoList;
    },
  },
  created() {
    this.$store.dispatch('loadTodos');
  },
  methods: {
    addTask() {
      this.$store.commit('addTodo', { id: Date.now(), title: this.addTodoName, completed: false });
      this.addTodoName = '';
    },
  },
};
</script>
<style lang="scss" scoped>
.todo {
  width: 480px;
  margin: 0 auto;
  padding: 24px;
  overflow: hidden;
  background: #fff;
  border-radius: 16px;
  .title {
    margin-bottom: 24px;
    font-weight: bold;
    font-size: 24px;
  }
  .add-todo {
    display: flex;
    justify-content: space-between;
    width: 100%;
    margin-bottom: 16px;
    input {
      width: 80%;
      padding-left: 16px;
      font-size: 24px;
      border: 1px solid #ccc;
      border-radius: 3px;
      outline: none;
      transition: all 0.3s ease;
    }
  }
}
</style>
